function wd=uwd
% uwd "useful" working drive - pwd but replace google drive path 
%
% This code is embarassingly hard-wired, but pretty useful. 
%
%  works because I have set up symbolic links 
%
% 
wd=pwd;

wd=strrep(wd,...
    '/Users/jsgerber/Library/CloudStorage/GoogleDrive-james.gerber@drawdown.org/Shared drives/Nexus Data Drive/',...
    '~/nexus/NexusDataDrive/');

wd=strrep(wd,...
    '/Users/jsgerber/Library/CloudStorage/GoogleDrive-james.gerber@drawdown.org/Shared drives/Geospatial Drive/DataProducts',...
    '~/DataProducts/');

wd=strrep(wd,...
    '/Users/jsgerber/Library/CloudStorage/GoogleDrive-james.gerber@drawdown.org/Shared drives/Geospatial Drive/Solutions-Explorer/MatlabSolutionSandbox/',...
    '~/DrawdownSolutions/');

wd=strrep(wd,...
    '/Users/jsgerber/Library/CloudStorage/GoogleDrive-james.gerber@drawdown.org/Shared drives/Solutions Assessment/Solutions/Food, Agriculture, Land & Ocean Nature-Based Carbon Removal/',...
    '~/shareddrives/Solutions/FOLU/');

wd=strrep(wd,...
    '/Users/jsgerber/Library/CloudStorage/GoogleDrive-james.gerber@drawdown.org/Shared drives/Solutions Assessment/Solutions/Electricity/',...
    '~/shareddrives/Solutions/Electricity/');

wd=strrep(wd,...
    '/Users/jsgerber/Library/CloudStorage/GoogleDrive-james.gerber@drawdown.org/Shared drives/', ...
    '~/shareddrives/')
