function cl=sixcrops
% SIXCROPS - get the names of the six crops out of 10 main crops less MWRS
%
% SYNTAX
% c=sixcrops - set c to a cell array of the sixteen main crops

cl={'barley',...
'cassava',...
'oilpalm',...
'rapeseed',...
'sorghum',...
'sugarcane'};
