function cl=sixteencrops
% SIXTEENCROPS - get the names of the sixteen main crops
%
% SYNTAX
% c=sixteencrops - set c to a cell array of the sixteen main crops

cl={'barley',...
'cassava',...
'groundnut',...
'maize',...
'millet',...
'oilpalm',...
'potato',...
'rapeseed',...
'rice',...
'rye',...
'sorghum',...
'soybean',...
'sugarbeet',...
'sugarcane',...
'sunflower',...
'wheat'};
