function [cl,clcotton]=sixteenRFcrops(IP)
% sixteenRFcrops - get the names of the sixteen main crops with irrigated
%
% SYNTAX
% [croplist,croplistwithcotton]=sixteenRFcrops(IP) 
%
% Example
% [~,croplistwithcotton]=sixteenRFcrops(20);

IPstr=int2str(IP);

cl={['barleyRF'  IPstr '_politunitirrfiltered'],...
['cassavaRF'  IPstr '_politunitirrfiltered'],...
['groundnutRF'  IPstr '_politunitirrfiltered'],...
['maizeRF'  IPstr '_politunitirrfiltered'],...
['milletRF'  IPstr '_politunitirrfiltered'],...
['oilpalmRF'  IPstr '_politunitirrfiltered'],...
['potatoRF'  IPstr '_politunitirrfiltered'],...
['rapeseedRF'  IPstr '_politunitirrfiltered'],...
['riceRF'  IPstr '_politunitirrfiltered'],...
['ryeRF'  IPstr '_politunitirrfiltered'],...
['sorghumRF'  IPstr '_politunitirrfiltered'],...
['soybeanRF'  IPstr '_politunitirrfiltered'],...
['sugarbeetRF'  IPstr '_politunitirrfiltered'],...
['sugarcaneRF'  IPstr '_politunitirrfiltered'],...
['sunflowerRF'  IPstr '_politunitirrfiltered'],...
['wheatRF'  IPstr '_politunitirrfiltered']};


clcotton={['barleyRF'  IPstr '_politunitirrfiltered'],...
['cassavaRF'  IPstr '_politunitirrfiltered'],...
['cottonRF'  IPstr '_politunitirrfiltered'],...
['groundnutRF'  IPstr '_politunitirrfiltered'],...
['maizeRF'  IPstr '_politunitirrfiltered'],...
['milletRF'  IPstr '_politunitirrfiltered'],...
['oilpalmRF'  IPstr '_politunitirrfiltered'],...
['potatoRF'  IPstr '_politunitirrfiltered'],...
['rapeseedRF'  IPstr '_politunitirrfiltered'],...
['riceRF'  IPstr '_politunitirrfiltered'],...
['ryeRF'  IPstr '_politunitirrfiltered'],...
['sorghumRF'  IPstr '_politunitirrfiltered'],...
['soybeanRF'  IPstr '_politunitirrfiltered'],...
['sugarbeetRF'  IPstr '_politunitirrfiltered'],...
['sugarcaneRF'  IPstr '_politunitirrfiltered'],...
['sunflowerRF'  IPstr '_politunitirrfiltered'],...
['wheatRF'  IPstr '_politunitirrfiltered']};