function [cl,clcotton]=sixteenIRRcrops(IP)
% sixteenIRRcrops - get the names of the sixteen main crops with irrigated
%
% SYNTAX
% [croplist,croplistwithcotton]=sixteenIRRcrops(IP) 
%
% Example
% [~,croplistwithcotton]=sixteenIRRcrops(20);

IPstr=int2str(IP);

cl={['barleyIRR'  IPstr '_politunitirrfiltered'],...
['cassavaIRR'  IPstr '_politunitirrfiltered'],...
['groundnutIRR'  IPstr '_politunitirrfiltered'],...
['maizeIRR'  IPstr '_politunitirrfiltered'],...
['milletIRR'  IPstr '_politunitirrfiltered'],...
['oilpalmIRR'  IPstr '_politunitirrfiltered'],...
['potatoIRR'  IPstr '_politunitirrfiltered'],...
['rapeseedIRR'  IPstr '_politunitirrfiltered'],...
['riceIRR'  IPstr '_politunitirrfiltered'],...
['ryeIRR'  IPstr '_politunitirrfiltered'],...
['sorghumIRR'  IPstr '_politunitirrfiltered'],...
['soybeanIRR'  IPstr '_politunitirrfiltered'],...
['sugarbeetIRR'  IPstr '_politunitirrfiltered'],...
['sugarcaneIRR'  IPstr '_politunitirrfiltered'],...
['sunflowerIRR'  IPstr '_politunitirrfiltered'],...
['wheatIRR'  IPstr '_politunitirrfiltered']};


clcotton={['barleyIRR'  IPstr '_politunitirrfiltered'],...
['cassavaIRR'  IPstr '_politunitirrfiltered'],...
['cottonIRR'  IPstr '_politunitirrfiltered'],...
['groundnutIRR'  IPstr '_politunitirrfiltered'],...
['maizeIRR'  IPstr '_politunitirrfiltered'],...
['milletIRR'  IPstr '_politunitirrfiltered'],...
['oilpalmIRR'  IPstr '_politunitirrfiltered'],...
['potatoIRR'  IPstr '_politunitirrfiltered'],...
['rapeseedIRR'  IPstr '_politunitirrfiltered'],...
['riceIRR'  IPstr '_politunitirrfiltered'],...
['ryeIRR'  IPstr '_politunitirrfiltered'],...
['sorghumIRR'  IPstr '_politunitirrfiltered'],...
['soybeanIRR'  IPstr '_politunitirrfiltered'],...
['sugarbeetIRR'  IPstr '_politunitirrfiltered'],...
['sugarcaneIRR'  IPstr '_politunitirrfiltered'],...
['sunflowerIRR'  IPstr '_politunitirrfiltered'],...
['wheatIRR'  IPstr '_politunitirrfiltered']};