function cl=tencrops(varargin)
% TENCROPS - get the names of the sixteen main crops
%
% SYNTAX
% c=tencrops - set c to a cell array of the sixteen main crops

cl={'barley',...
'cassava',...
'maize',...
'oilpalm',...
'rapeseed',...
'rice',...
'sorghum',...
'soybean',...
'sugarcane',...
'wheat'};

if nargin==1

    x=varargin{1};
    if numel(x)>1
        
        cl=cl(x);
    else
        cl=cl{varargin{1}};
    end
end

