function fiveminutemat2netcdf(filename)
% fiveminutemat2netcdf - generate a .nc from a five minute .mat file
%
%  this function will read in a .mat file (takes wildcards, no .mat) and
%  find every variable within there of 4320 2160 dimensions, and write them
%  out to a .nc file.  Useful for sharing some of our matfiles.
%
%  ways I can think of to make it crash:  
%  use *.mat as a wildcard (since it adds .mat at the end) [easy to fix]
%  give it a mat file with a type that can't be written as a .nc  [here,
%  i'm not sure best way to fix ... easy to cast variables, but they might
%  be some type for a reason.  would be a good idea to at least give the
%  user options.]

if nargin==0
    filename='*';
end

if numel(findstr(filename,'*'))>0
    a=dir([filename '*.mat']);
    
    for j=1:length(a)
        fiveminutemat2netcdf(a(j).name);
    end
    return
end


x=load(filename);

fn=fieldnames(x)

datastack=datablank;
datacount=0;
    clear DAS
DAS.notes=['This .nc autogenerated from ' filename ' using code ' mfilename ' on ' datestr(now)];
for j=1:length(fn);
   if isequal(size(getfield(x,fn{j})),[4320 2160])
       datacount=datacount+1;
       datastack(:,:,datacount)=getfield(x,fn{j});
       eval(['DAS.Field' int2str(datacount) '=' '''' fn{j} '''' ';']);
   end
   
   if datacount==2
       warndlg([ mfilename ' has never been tested with multiple layers. make sure it works, then remove this warndlg']);
      
   end
   
   
end

writenetcdf(datastack,'',strrep(filename,'.nc','.mat'),DAS);




